[r6s]
triggers = [
    "seegx",
]
responses = [
    "https://cdn.discordapp.com/attachments/746415517350363176/1362732917247184946/yan.gif?ex=6803776d&is=680225ed&hm=296e35890565c0ef3bad94dc4feb62ba082140011fa9e06a5cdc3317a5bc747a&",
    "https://cdn.discordapp.com/attachments/738831293864738975/1229465125514383421/reac.gif?ex=662fc7a0&is=661d52a0&hm=665f85732c43985759fc8acbdc3a7d3a073abd94350d56d3d8d9d693083cd9cc&",
]
comments = [
    "yaniu shooting at maestro cam",
    "yaniu reaction time",
]
weights = [
    10,
    10,
]

[sex]
triggers = [
    "sex",
    "segs",
    "seggs",
    "freak",
    "freaky",
    "freaki",
    "freek",
    "freeki",
    "sexo",
]
responses = [
    "https://cdn.discordapp.com/attachments/738831293864738975/1229998157941833758/segs-arona.gif?ex=6631b80d&is=661f430d&hm=08dce8539c48abe0a9ccbefb101cd9309fff33148e35b546facda55cbf4fae2e&",
    "https://media.discordapp.net/attachments/738548949488762954/888077474808877066/image0.gif?ex=6861fe59&is=6860acd9&hm=d1250a7438bbaa0f2d56e14b089bea997e87116148878667d88f626ab6e76e36&",
    "https://tenor.com/view/freddy-freddy-fazbear-fazbear-fazbear-pizza-place-freddy-hitting-gif-5328662341160349848",
    "https://cdn.discordapp.com/emojis/755791875008364586.gif?v=1",
    "https://tenor.com/view/girls-band-cry-gif-9261521843907890427",
    "https://cdn.discordapp.com/attachments/738831293864738975/1381883442957914203/RDT_20250608_1907062145042502345051570.gif?ex=68622f3e&is=6860ddbe&hm=5502822015bd229e9b600baed397a87d445c68f3588c79f3ce7a7c3289a784f3&",
    "https://tenor.com/view/touhou-orin-okuu-utsuho-utsuho-reiuji-gif-3335087173985524435",
    "https://tenor.com/view/fumo-fumo-sex-touhou-touhou-project-alimari-gif-4147126675707309296",
    "https://cdn.discordapp.com/attachments/1203774243062550610/1222485081600294933/image0.gif?ex=68625ff4&is=68610e74&hm=6a8633f33d294ee1280fce45deef455d6e80eae2474b9aef725d670dc7ad9336&",
    "https://tenor.com/view/tetris-tetris-sex-gif-25857618",
    "https://cdn.discordapp.com/attachments/677548756262060044/1383556936775110769/1749936067580.gif",
    "https://tenor.com/view/mococo-fuwamoco-vtuber-hololive-mococo-lick-gif-16937631731854129467",
]
comments = [
    "arona sex",
    "youmu_sex",
    "freaky_fredi",
    "korone_sex",
    "nina_subaru_sex",
    "doro_sex",
    "orin_utsuho_sex",
    "marialice_sex",
    "shiroko_lick_aggressive",
    "tetris_sex",
    "tight_kagami",
    "mogojohn_freaky_style",
]
weights = [
    10,
    10,
    10,
    10,
    10,
    10,
    10,
    10,
    10,
    10,
    10,
    10,
]

[teto]
triggers = [
    "teto",
    "tito",
]
responses = [
    "https://tenor.com/view/teto-kasane-teto-teto-plush-kasane-teto-plush-crush-it-gif-16166927453889012815",
    "https://tenor.com/view/teto-kasane-teto-teto-plush-kasane-teto-plush-vocaloid-gif-294642307665203507",
    "https://tenor.com/view/teto-kasane-teto-teto-plush-kasane-teto-plush-vocaloid-gif-13393804044482882953",
    "https://tenor.com/view/teto-kasane-teto-teto-plush-utau-utaloid-gif-667987304011719313",
    "https://tenor.com/view/crumble-teto-kasane-teto-teto-kasane-teto-utau-gif-5618160283985652736",
    "https://tenor.com/view/teto-fumo-spinning-kasane-teto-utau-gif-23200381",
    "https://tenor.com/view/yippee-yippee-gif-teto-teto-kasane-kasane-gif-309203518793187813",
    "https://tenor.com/view/kasane-teto-kasane-teto-ice-cream-gif-8045064054851668588",
    "https://media.tenor.com/KCp-ZpPXVrMAAAAM/kasane-teto-head-pat.gif",
]
comments = [
    "teto_crush",
    "teto_slice",
    "teto_inflate",
    "teto_squish",
    "teto_crumble",
    "teto_fumo_png_spinning",
    "teto_yipee",
    "teto_ice_cream",
    "high_quality_teto_plush.png",
]
weights = [
    10,
    10,
    10,
    10,
    10,
    10,
    10,
    10,
    10,
]

[goofy_aa_big_head]
triggers = [
    "big head",
]
responses = [
    "balls",
    "yaa",
    "eeee",
    "wejbl;kjweqrbujolwe",
]
comments = [
    "response 1",
    "response 2",
    "response 3",
    "response 4",
]
weights = [
    5,
    4,
    3,
    2,
]

[got_pinged_text]
triggers = []
responses = [
    "no",
    "i disagree",
    "kys",
]
comments = [
    "---",
    "---",
    "---",
]
weights = [
    10,
    5,
    1,
]

[got_pinged_gif]
triggers = []
responses = [
    "https://tenor.com/view/blue-archive-amd-hoshino-takanashi-hoshino-dancing-gif-10581432706103341722",
    "https://tenor.com/view/dance-dancing-ba-blue-archive-hoshino-gif-7432820339922762118",
    "https://tenor.com/view/takanashi-hoshino-blue-archive-hoshino-dance-hoshino-hoshino-blue-archive-gif-8449320256698247153",
    "https://tenor.com/view/takanashi-hoshino-blue-archive-cunny-archive-hoshino-my-beloved-hoshinohoshinohoshino-gif-24835592",
]
comments = [
    "hoshino_dancing_1",
    "hoshino_dancing_2",
    "hoshino_dancing_wiggle",
    "hoshino_vibrate",
]
weights = [
    4,
    4,
    2,
    1,
]
