[default_wrong_usage]
triggers = [

]
responses = [
    "kys",
    "go fucking kill yourself",
    "kill yourself",
    "use it properly",
    "nice one",
    "daem",
    "bruh",
    "wtf man"
]
comments = [
    "---",
    "---",
    "---",
    "---",
    "---",
    "---",
    "---",
    "---",
]
weights = [
    10,
    8,
    7,
    50,
    42,
    32,
    63,
    54
]

