[default_wrong_usage]
responses = [
    "kys",
    "go fucking kill yourself",
    "kill yourself",
    "use it properly",
    "nice one",
    "daem",
    "bruh",
    "wtf man"
]

weights = [
    10,
    8,
    7,
    50,
    42,
    32,
    63,
    54
]

[not_a_number]
responses=[
    "thats not a number retard",
    "thats definetly a number"
]

weights = [
    10,
    2
]